---
Name: fio-errored
---
SilverStripe\Control\RequestHandler:
  extensions:
    fioErrored: Fromholdio\Errored\Extensions\ControllerExtension

#Fromholdio\Errored\Errored:
#  dev_append_error_message: true
#  page_class: null
#  themes:
#    - '$public'
#    - 'silverstripe/login-forms:login-forms'
#    - '$default'
